exercism.org
exercism/swift pull request #555
Opened 2022-05-01 03:11 UTC by MenkeTechnologies

2022-05-01 18:07 UTC, NobbZ requested changes

2022-05-01 18:07 UTC, NobbZ commented on README.md
> +[Exercism](http://exercism.org) exercises in Swift
```suggestion
[Exercism](https://exercism.org) exercises in Swift
```

2022-05-01 18:07 UTC, NobbZ commented on docs/TESTS.md
> +This guide explains how to run unit tests for the Exercism Swift exercises using either macOS or Linux. It assumes you have already successfully installed the Exercism client and fetched the first ex
```suggestion
This guide explains how to run unit tests for the Exercism Swift exercises using either macOS or Linux. It assumes you have already successfully installed the Exercism client and fetched the first exercise. If not, [do that now](https://exercism.org/languages/swift).
```

2022-12-02 10:28 UTC, kytrinyx approved these changes

2022-12-02 10:38 UTC, merged